version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          sleep 60
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          sleep 60
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          sleep 60

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lint
      - test:
          requires: 
            - lint
      - build:
          requires:
            - test

